### ISSUE TITLE
ios下面mixins状态和数据自动清空

### ISSUE THREAD

**Issue by xrjxs** [tinajs/tinax#2]
```
Page.define(({
  mixins: [
    store.connect({
      state (state) {
        console.log('refrsh data')
        return {
          user: state.user,
          formData: {
            userId: "",
            phone: "",
          }
        }
      },
    }),
  ],
```

以上示例代码，ios下面当表单输入 userId, phone 数据时，切换应用或返回桌面，再次返回微信小程序时，输入的数据会被自动清空，打印 refresh data，但在安卓下面正常，数据没有清空，也没有打印 refresh data，请问这是什么原因？

**Comment by imyelo** [comment]
输入 userId, phone 数据时，有绑定什么 handler 吗？比如 `setData({ formData: userId, phone })` 或者通过 tinax 的 actions 同步到全局 state 当中。

**Comment by imyelo** [comment]
1. 从描述上看，应该是微信在 iOS 和安卓里对 [Page 生命周期](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F) 的实现逻辑有差异，所以导致了最终两个系统里的表现不一致。
2. 当 tinax 遇到了以下任一事件，都会及时将值同步给绑定了 `store.connect` 的页面或组件：
  - 页面触发 `onLoad`
  - 组件触发 `attached`
  - state 的值发生了变化

具体到上面的示例，例如在 iOS 中：
1. 打开页面。触发了 `onLoad`，tinax 将 `state()` 方法的返回值同步给了页面；即 `{ user: state.user, formData: { userId: '', phone: '' } }`。
2. 在页面的表单中输入 userId 和 phone 数据。
3. 切换应用或返回桌面，然后再次返回小程序。触发了 `onLoad`，所以 tinax 再次执行 `state()` 方法，并将返回值同步给页面，即 `{ user: state.user, formData: { userId: '', phone: '' } }`。

而安卓中应该是第 3 步不会触发 `onLoad`。


在实际应用里，页面自己管理的数据 (如 `formData`) 的初始值不应该写在 `state()`，而是直接赋值在 `data` 中即可，例如：

```javascript
Page.define({
  mixins: [
    store.connect({
      state (state) {
        return {
          user: state.user,
        }
      },
    }),
  ],
  data: {
    formData: {
      userId: '',
      phone: '',
    },
  },
  methods: {
    onFormChange ({ userId, phone }) {
      this.setData({
        formData: {
          userId,
          phone,
        },
      })
    },
  },
})
```

**Comment by xrjxs** [comment]
formData 放在 state() 里主要是想初始化 userId 的值，在 data 里写好像还要再次手动 setData

```
Page.define(({
  mixins: [
    store.connect({
      state (state) {
        console.log('refrsh data')
        return {
          user: state.user,
          formData: {
            userId: state.user.userId,
            phone: "",
          }
        }
      },
    }),
  ],
```

**Comment by xrjxs** [comment]
经过测试 formData 放在 data 里确实不会再触发 state() 导致数据清空
